Repository thealoksingh/Hisab-Kitab, pull requests merged in 2025-01, with the labels that each got.

#7 Friend request api merge to main
  src/main/java/com/hisabKitab/springProject/controller/FriendRequestController.java
  src/main/java/com/hisabKitab/springProject/entity/FriendRequestEntity.java
  src/main/java/com/hisabKitab/springProject/entity/UserEntity.java
  src/main/java/com/hisabKitab/springProject/repository/FriendRequestRepository.java
  src/main/java/com/hisabKitab/springProject/service/FriendRequestService.java
  src/main/java/com/hisabKitab/springProject/service/UserService.java
Labels: bug

#9 merging Add email notification into main
  pom.xml
  src/main/java/com/hisabKitab/springProject/controller/UserController.java
  src/main/java/com/hisabKitab/springProject/service/EmailNotificationService.java
Labels: enhancement, good first issue

#18 Merging Modify readme file into netlify hosting
  README.md
  target/classes/com/hisabKitab/springProject/HisabKitabApplication.class
  target/classes/com/hisabKitab/springProject/controller/AdminController.class
  target/classes/com/hisabKitab/springProject/controller/FriendRequestController.class
  target/classes/com/hisabKitab/springProject/controller/FriendTransactionController.class
  target/classes/com/hisabKitab/springProject/controller/ReportData.class
  target/classes/com/hisabKitab/springProject/controller/TransactionCommentController.class
  target/classes/com/hisabKitab/springProject/controller/TransactionReportController.class
  target/classes/com/hisabKitab/springProject/controller/UserController.class
  target/classes/com/hisabKitab/springProject/dto/CommentRequestDto.class
  target/classes/com/hisabKitab/springProject/dto/CommentResponseDto.class
  target/classes/com/hisabKitab/springProject/dto/GetFriendListDto.class
  target/classes/com/hisabKitab/springProject/dto/SignUpUserDto.class
  target/classes/com/hisabKitab/springProject/dto/TransactionDetailsDto.class
  target/classes/com/hisabKitab/springProject/dto/UsersFriendEntityDto.class
  target/classes/com/hisabKitab/springProject/entity/Balance.class
  target/classes/com/hisabKitab/springProject/entity/FriendRequestEntity.class
  target/classes/com/hisabKitab/springProject/entity/Transaction.class
  target/classes/com/hisabKitab/springProject/entity/TransactionComment.class
  target/classes/com/hisabKitab/springProject/entity/UserEntity.class
  target/classes/com/hisabKitab/springProject/repository/BalanceRepository.class
  target/classes/com/hisabKitab/springProject/repository/FriendRequestRepository.class
  target/classes/com/hisabKitab/springProject/repository/TransactionCommentsRepository.class
  target/classes/com/hisabKitab/springProject/repository/TransactionRepository.class
  target/classes/com/hisabKitab/springProject/repository/UserRepository.class
  target/classes/com/hisabKitab/springProject/service/BalanceService.class
  target/classes/com/hisabKitab/springProject/service/CommentService.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService$1.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService$2.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService.class
  target/classes/com/hisabKitab/springProject/service/FriendRequestService.class
  target/classes/com/hisabKitab/springProject/service/TransactionReportService.class
  target/classes/com/hisabKitab/springProject/service/TransactionService.class
  target/classes/com/hisabKitab/springProject/service/UserService.class
  target/test-classes/com/hisabKitab/springProject/HisabKitabApplicationTests.class
Labels: documentation, enhancement, good first issue

#19 Merging modify-readme-file into netlify-hosting
  README.md
  src/main/java/com/hisabKitab/springProject/dto/FriendRequestStatus.java
  src/main/java/com/hisabKitab/springProject/service/EmailNotificationService.java
  src/main/java/com/hisabKitab/springProject/service/FriendRequestService.java
  target/classes/com/hisabKitab/springProject/controller/FriendRequestController.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService$2.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService.class
  target/classes/com/hisabKitab/springProject/service/FriendRequestService.class
Labels: documentation, enhancement, good first issue

#20 merging feature email notification while sending and accepting friend request from Netlify hosting into main
  README.md
  netlify.toml
  src/main/java/com/hisabKitab/springProject/dto/FriendRequestStatus.java
  src/main/java/com/hisabKitab/springProject/service/EmailNotificationService.java
  src/main/java/com/hisabKitab/springProject/service/FriendRequestService.java
  target/classes/com/hisabKitab/springProject/HisabKitabApplication.class
  target/classes/com/hisabKitab/springProject/controller/AdminController.class
  target/classes/com/hisabKitab/springProject/controller/FriendRequestController.class
  target/classes/com/hisabKitab/springProject/controller/FriendTransactionController.class
  target/classes/com/hisabKitab/springProject/controller/ReportData.class
  target/classes/com/hisabKitab/springProject/controller/TransactionCommentController.class
  target/classes/com/hisabKitab/springProject/controller/TransactionReportController.class
  target/classes/com/hisabKitab/springProject/controller/UserController.class
  target/classes/com/hisabKitab/springProject/dto/CommentRequestDto.class
  target/classes/com/hisabKitab/springProject/dto/CommentResponseDto.class
  target/classes/com/hisabKitab/springProject/dto/GetFriendListDto.class
  target/classes/com/hisabKitab/springProject/dto/SignUpUserDto.class
  target/classes/com/hisabKitab/springProject/dto/TransactionDetailsDto.class
  target/classes/com/hisabKitab/springProject/dto/UsersFriendEntityDto.class
  target/classes/com/hisabKitab/springProject/entity/Balance.class
  target/classes/com/hisabKitab/springProject/entity/FriendRequestEntity.class
  target/classes/com/hisabKitab/springProject/entity/Transaction.class
  target/classes/com/hisabKitab/springProject/entity/TransactionComment.class
  target/classes/com/hisabKitab/springProject/entity/UserEntity.class
  target/classes/com/hisabKitab/springProject/repository/BalanceRepository.class
  target/classes/com/hisabKitab/springProject/repository/FriendRequestRepository.class
  target/classes/com/hisabKitab/springProject/repository/TransactionCommentsRepository.class
  target/classes/com/hisabKitab/springProject/repository/TransactionRepository.class
  target/classes/com/hisabKitab/springProject/repository/UserRepository.class
  target/classes/com/hisabKitab/springProject/service/BalanceService.class
  target/classes/com/hisabKitab/springProject/service/CommentService.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService$1.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService$2.class
  target/classes/com/hisabKitab/springProject/service/EmailNotificationService.class
  target/classes/com/hisabKitab/springProject/service/FriendRequestService.class
  target/classes/com/hisabKitab/springProject/service/TransactionReportService.class
  target/classes/com/hisabKitab/springProject/service/TransactionService.class
  target/classes/com/hisabKitab/springProject/service/UserService.class
  target/test-classes/com/hisabKitab/springProject/HisabKitabApplicationTests.class
Labels: enhancement, good first issue

#23 Bug fix of invitation mail, signup otp and forget password otp
  README.md
  src/main/java/com/hisabKitab/springProject/controller/UserController.java
  src/main/java/com/hisabKitab/springProject/service/UserService.java
  target/classes/com/hisabKitab/springProject/controller/UserController.class
  target/classes/com/hisabKitab/springProject/service/UserService.class
Labels: bug, good first issue
